_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "3":
                - 2
                - 17
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.8
            "8":
                - 1
                - 3
                - 5
            "10":
                - 3
            "12": 0.19.8
            "13": windows-amd64
